name: GitHub Metrics

on:
schedule:
- cron: "0 0 * * *"

workflow_dispatch:

push:
branches:
- main
- master

jobs:
github-metrics:
runs-on: ubuntu-latest

permissions:
  contents: write

steps:
  - name: Generate GitHub Metrics
    uses: lowlighter/metrics@latest
    with:
      token: ${{ secrets.METRICS_TOKEN }}

      filename: github-metrics.svg

      config_timezone: America/Sao_Paulo
      config_theme: dark

      base: header, activity, community, repositories, metadata
      base_indepth: yes

      plugin_languages: yes
      plugin_languages_ignored: >-
        html,css,tex,less,dockerfile,makefile,qmake,lex,cmake,
        shell,gnuplot

      plugin_languages_limit: 8
      plugin_languages_details: percentage

  - name: Generate SPM Repository Card
    uses: lowlighter/metrics@latest
    with:
      token: ${{ secrets.METRICS_TOKEN }}

      filename: spm-repo.svg

      user: spm-ecosystem
      repo: site-package-manager

      template: repository
      config_theme: dark

      plugin_languages: yes
      plugin_languages_ignored: html,css
      plugin_languages_limit: 4

  - name: Generate GateBridge Repository Card
    uses: lowlighter/metrics@latest
    with:
      token: ${{ secrets.METRICS_TOKEN }}

      filename: gatebridge-repo.svg

      user: watashi-00
      repo: gatebridge

      template: repository
      config_theme: dark

      plugin_languages: yes
      plugin_languages_ignored: html,css
      plugin_languages_limit: 4
